### ISSUE TITLE
Initialize an express project

### ISSUE THREAD

**Issue by sheldor1510** [Tech-Shell/subtle#1]
Create the starter files for an express project.

**Comment by gigabite-pro** [comment]
Can i work on this issue?

**Comment by devil-cyber** [comment]
I would like to work on this project. Can you provide me some details

**Comment by sheldor1510** [comment]
> Can I work on this issue?

@gigabite-pro yeah sure.

**Comment by devil-cyber** [comment]
Ok thanks

**Comment by sheldor1510** [comment]
thanks for contributing.
